Fix a missing import for datetime
Resolves:

```
"/Users/daniel.eck/Documents/workspace/kohls-dce/worker-tmp/src/worker.py",
line 69, in inner
    result = func(body)
  File
"/Users/daniel.eck/Documents/workspace/kohls-dce/worker-tmp/src/worker.py",
line 109, in callback
    worker_start_time = dt.datetime.today()
NameError: name 'dt' is not defined
```